version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: dost_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "2100:2100"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: dost_frontend
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - "2101:2101"
    stdin_open: true
    tty: true
