version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: dost_backend
    restart: unless-stopped
    environment:
      API_PORT: 2100
      DB_HOST: 192.168.0.41
      DB_USER: sintauser
      DB_PASSWORD: s!in++a2026
      DB_NAME: sinta
      DB_PORT: 3521
    ports:
      - "2100:2100"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: dost_frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    ports:
      - "2101:2101"
    stdin_open: true
    tty: true

