FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Build the production app
RUN npm run build

# Install serve to run the production build
RUN npm install -g serve

EXPOSE 2101

# Serve the build folder on port 2101
CMD ["serve", "-s", "build", "-l", "2101"]
